apiVersion: v2
name: onyx
version: 0.0.15
appVersion: "v0.26.0"
description: Gen-AI Chat for Teams - Think ChatGPT if it had access to your team's unique knowledge.
home: https://www.onyx.app/
sources:
  - "https://github.com/zadarastorage/helm-charts/blob/main/charts/onyx"
  - "https://github.com/onyx-dot-app/onyx"
maintainers:
  - name: eric-zadara
    url: https://github.com/eric-zadara
dependencies:
  - name: redis
    version: 20.1.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: cluster
    version: 0.0.11
    repository: https://cloudnative-pg.github.io/charts
    alias: cnpg
    condition: cnpg.enabled
  - name: vespa-ai
    version: 0.0.2
    repository: https://zadarastorage.github.io/helm-charts
    #repository: "file://../vespa-ai"
    alias: vespa
    condition: vespa.enabled
#  - name: vespa
#    version: 0.2.3
#    repository: https://unoplat.github.io/vespa-helm-charts
#    condition: vespa.enabled
